version: '3'

services:
  soc:
    container_name: soc
    image: soc
    build: ./soc
    stdin_open: true
    tty: true    
    volumes:
      - soc_data:/root/data       
    network_mode: host
    
volumes:
  soc_data:
    name: soc_data
